fof(trans, axiom, ! [X,Y,Z] : ((rel(X,Y) & rel(Y,Z)) => rel(X,Z))).
fof(link0, axiom, rel(a0, a1)).
fof(link1, axiom, rel(a1, a2)).
fof(link2, axiom, rel(a2, a3)).
fof(link3, axiom, rel(a3, a4)).
fof(link4, axiom, rel(a4, a5)).
fof(link5, axiom, rel(a5, a6)).
fof(link6, axiom, rel(a6, a7)).
fof(link7, axiom, rel(a7, a8)).
fof(link8, axiom, rel(a8, a9)).
fof(link9, axiom, rel(a9, a10)).
fof(link10, axiom, rel(a10, a11)).
fof(link11, axiom, rel(a11, a12)).
fof(link12, axiom, rel(a12, a13)).
fof(dfact0, axiom, other(b0, b1)).
fof(dfact1, axiom, other(b1, b2)).
fof(dfact2, axiom, other(b2, b3)).
fof(dfact3, axiom, other(b3, b4)).
fof(dfact4, axiom, other(b4, b5)).
fof(dfact5, axiom, other(b5, b6)).
fof(dfact6, axiom, other(b6, b7)).
fof(dfact7, axiom, other(b7, b8)).
fof(goal, conjecture, rel(a0, a13)).
